/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.neurpheus.classification.neuralnet.designer;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.Serializable;
import java.util.logging.Logger;
import org.neurpheus.classification.neuralnet.designer.palette.PaletteSupport;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.Utilities;
import org.openide.util.lookup.Lookups;

/**
 * Top component which displays something.
 */
final class NueralNetworkDesignerTopComponent extends TopComponent {

    private static NueralNetworkDesignerTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "org/neurpheus/classification/neuralnet/designer/smallnet.gif";

    private static final String PREFERRED_ID = "NueralNetworkDesignerTopComponent";

    private Component myView;
    
    private NueralNetworkDesignerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(NueralNetworkDesignerTopComponent.class, "CTL_NueralNetworkDesignerTopComponent"));
        setToolTipText(NbBundle.getMessage(NueralNetworkDesignerTopComponent.class, "HINT_NueralNetworkDesignerTopComponent"));
        setIcon(Utilities.loadImage(ICON_PATH, true));
        DesignScene scene = new DesignScene();
        myView = scene.createView();
        shapePane.setViewportView(myView);
        add(scene.createSatelliteView(), BorderLayout.WEST);        
        associateLookup( Lookups.fixed( new Object[] { PaletteSupport.createPalette() } ) );        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapePane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(shapePane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane shapePane;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized NueralNetworkDesignerTopComponent getDefault() {
        if (instance == null) {
            instance = new NueralNetworkDesignerTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the NueralNetworkDesignerTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized NueralNetworkDesignerTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(NueralNetworkDesignerTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof NueralNetworkDesignerTopComponent) {
            return (NueralNetworkDesignerTopComponent) win;
        }
        Logger.getLogger(NueralNetworkDesignerTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
    // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
    // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return NueralNetworkDesignerTopComponent.getDefault();
        }
    }
}
